# Generated by Django 5.1.3 on 2024-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=150)),
                ("club", models.CharField(max_length=150)),
                ("price", models.IntegerField()),
                ("post", models.CharField(max_length=150)),
            ],
        ),
    ]
