# Generated by Django 5.1.3 on 2024-12-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fplayers", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="country",
            new_name="nationality",
        ),
        migrations.RemoveField(
            model_name="player",
            name="name",
        ),
        migrations.RemoveField(
            model_name="player",
            name="post",
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_birthday",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="player",
            name="lastname",
            field=models.CharField(
                default="Player Last Name",
                max_length=300,
                unique=True,
                verbose_name="Lastname",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("Attaquant", "Attaquant"),
                    ("Milieu", "Milieu"),
                    ("Défenseur", "Défenseur"),
                    ("Gardien", "Gardien"),
                ],
                default="Attaquant",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="surname",
            field=models.CharField(
                default="Player Surname",
                max_length=300,
                unique=True,
                verbose_name="Surname",
            ),
        ),
    ]
