# Generated by Django 5.1.3 on 2024-12-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fplayers",
            "0002_rename_country_player_nationality_remove_player_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="photo",
            field=models.ImageField(null=True, upload_to="player_photo"),
        ),
    ]
