# Generated by Django 5.1.3 on 2024-12-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fplayers", "0005_rename_photo_player_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.ImageField(null=True, upload_to="player_image"),
        ),
    ]
