# Generated by Django 5.1.3 on 2024-12-05 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fplayers", "0007_player_assists_player_goals"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="surname",
            new_name="firstname",
        ),
    ]
