# Generated by Django 5.1.3 on 2024-12-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fplayers", "0010_alter_player_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="firstname",
            field=models.CharField(max_length=300, verbose_name="Firstname"),
        ),
    ]
