# Generated by Django 5.1.3 on 2024-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fplayers", "0011_alter_player_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
